// Code generated by 'guts'. DO NOT EDIT.

export type Comparable = string | number | boolean;

// From nicloudsdk/generics.go
export interface Complex<C extends Comparable, S extends Single, T extends Custom> {
    readonly dynamic: Fields<C, boolean, string, S>;
    readonly order: FieldsDiffOrder<C, string, S, T>;
    readonly comparable: C;
    readonly single: S;
    readonly static: Static;
}

// From nicloudsdk/generics.go
export type Custom = string | boolean | number | number | string[] | (number | null);

// From nicloudsdk/generics.go
// biome-ignore lint lint/complexity/noUselessTypeConstraint: golang does 'any' for generics, typescript does not like it
export interface Dynamic<A extends any, S extends Single> {
    readonly dynamic: Fields<boolean, A, string, S>;
    readonly comparable: boolean;
}

// From nicloudsdk/generics.go
// biome-ignore lint lint/complexity/noUselessTypeConstraint: golang does 'any' for generics, typescript does not like it
export interface Fields<C extends Comparable, A extends any, T extends Custom, S extends Single> {
    readonly comparable: C;
    readonly any: A;
    readonly custom: T;
    readonly again: T;
    readonly single_constraint: S;
}

// From nicloudsdk/generics.go
// biome-ignore lint lint/complexity/noUselessTypeConstraint: golang does 'any' for generics, typescript does not like it
export interface FieldsDiffOrder<A extends any, C extends Comparable, S extends Single, T extends Custom> {
    readonly Fields: Fields<C, A, T, S>;
}

// From nicloudsdk/generics.go
export type Single = string;

// From nicloudsdk/generics.go
export interface Static {
    readonly static: Fields<string, number, number, string>;
}
