// Code generated by 'guts'. DO NOT EDIT.

// From nicloudsdk/enums.go
export type Enum = "bar" | "baz" | "foo" | "qux";

// From nicloudsdk/enums.go
export type EnumSliceType = readonly Enum[];

export const Enums: Enum[] = ["bar", "baz", "foo", "qux"];
